spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    druid:
      #配置监控统计拦截的filters,去掉后监控界面sql将无法统计，'wall'用于防火墙
      filters: stat,wall,log4j
      #最大活跃数
      max-active: 20
      #初始化数量
      initial-size: 1
      #最大连接等待超时时间
      max-wait: 60000
      #打开PSCache，并且指定每个PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      #通过connectionProperties属性来打开mergeSql功能,慢Sql记录
      connection-properties: druid.stat.meergeSql=true;druid.stat.slowSqlMillis=5000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      validation-query: select 1 from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: update

  #配置Redis数据库连接
  redis:
    host: 127.0.0.1
    port: 6379
    pool:
      max-idle: 20
      min-idle: 1
      max-active: 20
      max-wait: 60000
    database: 0 #默认是索引为0的数据库
